[package]
name = "primesieve-gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "22.0.0"
pollster = "0.3"
bytemuck = { version = "1.16.1", features = ["derive"] }
